DROP TABLE IF EXISTS job;
CREATE TABLE job (
	job_opportunity CHAR(255),
	job_id INT PRIMARY KEY NOT NULL,
	description TEXT,
	job_title TEXT,
	job_summary TEXT,
	job_description TEXT,
	research_field TEXT,
	main_research_field TEXT,
	sub_research_field TEXT,
	researcher_profile TEXT,
	type_of_contract CHAR(255),
	job_status CHAR(255),
	hours_per_week TEXT,
	job_start_date timestamp,
	application_deadline timestamp,
	science4refugees boolean,
	additional_information TEXT,
	comment TEXT,
	info_website CHAR(455),
	eu_funding CHAR(255),
	framework_programme CHAR(255),
	job_reference_number CHAR(255),
	work_location CHAR(255),
	nr_job_positions INT,
	job_organisation_institute TEXT,
	job_country CHAR(255),
	job_city CHAR(255),
	hiring_org_inst CHAR(255),
	organisation_institute CHAR(255),
	organisation_institute_type CHAR(255),
	country CHAR(255),
	e_mail CHAR(255),
	website CHAR(255),
	application_details CHAR(255),
	how_to_apply CHAR(255),
	application_email CHAR(255),
	benefits TEXT,
	required_research_experiences TEXT,
	research_sub_field TEXT,
	years_of_research_experience TEXT,
	additional_requirements TEXT,
	required_education_level TEXT,
	degree TEXT,
	discipline TEXT,
	required_languages TEXT,
	language VARCHAR(400),
	language_level VARCHAR (400),
	job_postal_code VARCHAR (255),
	job_street VARCHAR (400),
	division_faculty VARCHAR (400),
	city VARCHAR (400),
	postal_code VARCHAR (255),
	street VARCHAR (255),
	downloadtime timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	updatetime timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE job ALTER COLUMN application_details TYPE TEXT;
ALTER TABLE job ALTER COLUMN website TYPE TEXT;
ALTER TABLE job ALTER COLUMN organisation_institute TYPE TEXT;
